// auth constants
export const LOGOUT = 'LOGOUT';
export const SET_CURRENT_PARTICIPANT = 'SET_CURRENT_PARTICIPANT';

// tracking constants
export const START_TRACKING = 'START_TRACKING';
export const STOP_TRACKING = 'STOP_TRACKING';
export const AUTHORIZE_TRACKING = 'AUTHORIZE_TRACKING';
export const FOREGROUND_TRACKING = 'FOREGROUND_TRACKING';
export const BACKGROUND_TRACKING = 'BACKGROUND_TRACKING';
export const TRACKING_ERROR = 'TRACKING_ERROR';
export const LOCATION = 'LOCATION';
export const STATIONARY = 'STATIONARY';
